### ISSUE TITLE
SerializationException while fetching KafkaTrackingToken from JpaTokenStore after processor enters retry mode

### ISSUE THREAD

**Issue by shubhojitr** [AxonFramework/extension-kafka#34]
I'm using Axon 4.2 with extension-kafka 4.0-RC3
Below are the axon configurations used:
![image](https://user-images.githubusercontent.com/42104131/72314381-adc64500-36c9-11ea-908a-fa94f94941e1.png)

Application works fine and is able to consume events from kafka topic until there is any kind RuntimeException while handling an event. If a RuntimeException occurs during event handling the processor enters ERROR MODE as I'v configured `PropagatingErrorHandler`. During the 2nd retry onwards aoxn fails to fetch token because of jackson SerializationException. 

**token_entry before entring error mode:**
![image](https://user-images.githubusercontent.com/42104131/72314751-224db380-36cb-11ea-83c9-73628b75af71.png)

**Error Trace:**

> _**org.axonframework.serialization.SerializationException: Error while deserializing object
	at org.axonframework.serialization.json.JacksonSerializer.deserialize(JacksonSerializer.java:202)**
	at org.axonframework.eventhandling.tokenstore.AbstractTokenEntry.getToken(AbstractTokenEntry.java:117)
	at org.axonframework.eventhandling.tokenstore.jpa.JpaTokenStore.fetchToken(JpaTokenStore.java:167)
	at org.axonframework.eventhandling.TrackingEventProcessor.lambda$ensureEventStreamOpened$13(TrackingEventProcessor.java:474)
	at org.axonframework.common.transaction.TransactionManager.fetchInTransaction(TransactionManager.java:70)
	at org.axonframework.eventhandling.TrackingEventProcessor.ensureEventStreamOpened(TrackingEventProcessor.java:473)
	at org.axonframework.eventhandling.TrackingEventProcessor.processingLoop(TrackingEventProcessor.java:274)
	at org.axonframework.eventhandling.TrackingEventProcessor$TrackingSegmentWorker.run(TrackingEventProcessor.java:1071)
	at org.axonframework.eventhandling.TrackingEventProcessor$WorkerLauncher.run(TrackingEventProcessor.java:1183)
	at java.base/java.lang.Thread.run(Thread.java:834)
**Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot find a (Map) Key deserializer for type [simple type, class org.apache.kafka.common.TopicPartition]
 at [Source: (byte[])"{"positions":{"giftcard-topic-r4-4":0,"giftcard-topic-r4-3":6,"giftcard-topic-r4-0":0,"giftcard-topic-r4-2":0,"giftcard-topic-r4-1":0}}"; line: 1, column: 1]**
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._handleUnknownKeyDeserializer(DeserializerCache.java:599)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findKeyDeserializer(DeserializerCache.java:168)
	at com.fasterxml.jackson.databind.DeserializationContext.findKeyDeserializer(DeserializationContext.java:500)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.createContextual(MapDeserializer.java:248)
	at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:651)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:484)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
	at com.fasterxml.jackson.databind.ObjectReader._findRootDeserializer(ObjectReader.java:1895)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1606)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1234)
	at org.axonframework.serialization.json.JacksonSerializer.deserialize(JacksonSerializer.java:200)
	... 9 more_

**Comment by shubhojitr** [comment]
This seems to be happening only if jackson is configured as a serializer and I'm unable to replicate the same with DEFAULT/XSTREAM

**Comment by smcvb** [comment]
Thanks for filing this @shubhojitr. Seems that Kafka's `TopicPartition` class cannot be deserialized as expected. This will require a test and fix, which will surely be added to 4.0.

As a quick fix on your part, I would suggest to change the `general` serializer to `xstream` and use the `jackson` serializer for `messages` instead. That way, the `XStreamSerializer` will be used for Token (and Sagas, Snapshots..), whilst the `JacksonSerializer` will be used for all your messages.

**Comment by shubhojitr** [comment]
Thankyou for your suggestion @smcvb. I've changed  the `general` serializer to `xstream` and ` jackson` for `messages` and `events` serializer. I"m creating JpaTokenStore using below bean. I can see only Token is using `xstream` and for Messages/Sagas `jackson` is used. However I did not checked Snapshots. 

    @Bean
    public JpaTokenStore jpaTokenStore(@Autowired EntityManagerProvider entityManagerProvider,
            Serializer genericSerializer) {

        return JpaTokenStore.builder().serializer(genericSerializer)
                .entityManagerProvider(entityManagerProvider).build();
    }


My only concern was to be able to switch back to jackson once the fix is release. Now with only TOKEN_ENTRY to be taken care of while moving back to jackson should not be a big task.

What do think of the above configurartions and the idea to move back to jackson for Token once you provide a fix?

**Comment by smcvb** [comment]
Switching back would cost some effort indeed, as you'd have stored tokens in a form you cannot deal with once you change it from `xstream` to `jackson`. This could be resolved by a wrapper serializer containing both, which upon deserialization checks the format, but when serializes **always** uses `jackson`.

Having said this, we typically suggest to use `xstream` as the general serializes since it serializes virtually anything. Doing so ensure you do not have to add **any** Jackson annotations in your Sagas and Aggregates (the latter would be required when using snapshots). I feel this is beneficial, since Jackson annotations in your Saga/Aggregate only obstruct the true intent of said Saga/Aggregate.

Regardless, you are always free to choose which serializer you utilize for this part, and switching should be doable, definitely with the stated wrapper serializer in place.
